apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: memsql-cluster
    app.kubernetes.io/name: memsql-cluster
  name: svc-memsql-cluster-ddl-internal
  namespace: singlestore
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: memsql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: memsql-cluster
    app.kubernetes.io/name: memsql-cluster
    statefulset.kubernetes.io/pod-name: node-memsql-cluster-master-0
  sessionAffinity: None
  type: ClusterIP
