{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.memsqlOperatorDeployment.serviceAccountName}}
{{ if .Values.serviceAccount }}
{{if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.serviceAccount.imagePullSecrets}}
{{ end }}
{{ end }}
{{ end }}